// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwVORXkksYXWnkmHbfkSA54leCdQQQgAM',
    appId: '1:682464303997:web:c790e3e966467711e30a14',
    messagingSenderId: '682464303997',
    projectId: 'mainproject-db-test',
    authDomain: 'mainproject-db-test.firebaseapp.com',
    databaseURL: 'https://mainproject-db-test-default-rtdb.firebaseio.com',
    storageBucket: 'mainproject-db-test.firebasestorage.app',
    measurementId: 'G-SC9EM6LTJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOURl_gQ18q759IiLH22owrgauFl_wo-0',
    appId: '1:682464303997:android:7a63775c0748a815e30a14',
    messagingSenderId: '682464303997',
    projectId: 'mainproject-db-test',
    databaseURL: 'https://mainproject-db-test-default-rtdb.firebaseio.com',
    storageBucket: 'mainproject-db-test.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpKzKSPzq3XknE-fmbEWcBnA1D0O2lvFo',
    appId: '1:682464303997:web:9416121a395dc4dfe30a14',
    messagingSenderId: '682464303997',
    projectId: 'mainproject-db-test',
    authDomain: 'mainproject-db-test.firebaseapp.com',
    databaseURL: 'https://mainproject-db-test-default-rtdb.firebaseio.com',
    storageBucket: 'mainproject-db-test.firebasestorage.app',
    measurementId: 'G-RBHC973RF1',
  );
}
